### ISSUE TITLE
v0.5.1 doesn't run on Ubuntu 18.04

### ISSUE THREAD

**Issue by aigarashi** [jayhorn/jayhorn#151]
I tried to run v0.5.1 by following the instructions at https://github.com/jayhorn/jayhorn/releases.
The downloaded jar worked on Mac but didn't quite work on Ubuntu 18.04.  I tried 
- OpenJDK Runtime Environment (build 1.8.0_181-8u181-b13-0ubuntu0.18.04.1-b13)
- OpenJDK Runtime Environment (build 10.0.2+13-Ubuntu-1ubuntu0.18.04.1)

but both produce the same result below.  The problem seems that org.objectweb.asm is too old to run on newer JREs.

> $ java -jar jayhorn.jar -j tmp 
[root] - 		 ---   JAYHORN : Static Analayzer for Java Programs ---- 
[root] - 	 Verification : safety
[root] - 	 Solver : eldarica
[root] - Building CFG  ... 
2018-09-13 14:49:04,361 ERROR (main) [root] - java.lang.IllegalArgumentException
Exception in thread "main" java.lang.IllegalArgumentException
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:170)
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:153)
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:424)
	at soot.asm.AsmClassSource.read(AsmClassSource.java:55)
	at soot.asm.AsmClassSource.resolve(AsmClassSource.java:65)
	at soot.SootResolver.bringToHierarchy(SootResolver.java:239)
	at soot.SootResolver.bringToSignatures(SootResolver.java:266)
	at soot.SootResolver.processResolveWorklist(SootResolver.java:170)
	at soot.SootResolver.resolveClass(SootResolver.java:131)
	at soot.Scene.loadClass(Scene.java:707)
	at soot.Scene.loadClassAndSupport(Scene.java:692)
	at soot.Scene.loadNecessaryClasses(Scene.java:1367)
	at soottocfg.soot.SootRunner.loadClassesIntoScene(SootRunner.java:296)
	at soottocfg.soot.SootRunner.runWithPath(SootRunner.java:192)
	at soottocfg.soot.SootRunner.run(SootRunner.java:94)
	at soottocfg.soot.SootToCfg.run(SootToCfg.java:110)
	at jayhorn.Main.safetyAnalysis(Main.java:52)
	at jayhorn.Main.main(Main.java:100)

**Comment by martinschaef** [comment]
Looks like an issue with the ASM version that we are using. Any chance you could share your input with us?

**Comment by lememta** [comment]
I could potentially upgrade the version over the weekend.

**Comment by aigarashi** [comment]
The input was class files compiled from Maun.java but I'll attach the class files just in case.

[Maun.zip](https://github.com/jayhorn/jayhorn/files/2381515/Maun.zip)

**Comment by naokikob** [comment]
Is there any update on this issue?
I encountered the same problem.

**Comment by aigarashi** [comment]
It turns out that this was due to my mistake.  My Ubuntu Box has both JDK 8 and 11 installed and the class files are generated by javac from JDK 11 (run by JVM from JDK 8).  I removed JDK 11 and it seems that everything works fine. 

I'll close this issue.
