### ISSUE TITLE
Unsound result for test case

### ISSUE THREAD

**Issue by martinschaef** [jayhorn/jayhorn#152]
For some micro examples, Soot's optimizations lead to unsound results because some operations get simplified to no-ops. Below our intermediate for the failing test case [horn-encoding/regression/UnsatInstOf.java](https://github.com/jayhorn/jayhorn/blob/svcomp19/jayhorn/src/test/resources/horn-encoding/regression/UnsatInstOf.java). I'll see if I have more time to fix this later tonight, but I'm pretty booked with a conference this week.

```
Method <Main: void main(JayArray_java_lang_String)>($in_0, inHeapCounter)
  Return types: java.lang.Throwable, int
  Returns: java.lang.Throwable $ex_, int outHeapCounter

  locals:
    $assert_9:    boolean
    $r2:    Main
    $assert_7:    boolean
    $r3:    TYPE
Block0:
	return
Root ->Block1:
(ln 9)	outHeapCounter := 1
(ln 9)	assume (JayArray_java_lang_String $in_0#3 >= 0)
(ln 9)	push_102(JayArray_java_lang_String, $in_0, [JayArray_java_lang_String $in_0#3, undef_field0, undef_field1])
(ln 9)	$ex_, outHeapCounter := call <Main: void <clinit>()>(outHeapCounter)
(ln 9)	$ex_, outHeapCounter := call <JayHornAssertions: void <clinit>()>(outHeapCounter)
(ln 10)	outHeapCounter := (outHeapCounter + 1)
(ln 10)	$r2 := new Main
(ln 10)	$ex_, outHeapCounter := call <Main: void <init>()>($r2, outHeapCounter)
(ln 10)	$assert_7 := ($ex_ == $null$)
(ln 10)	assert $assert_7
(ln 12)	$r3 := Main $r2#1
(ln 12)	$assert_9 := ($ex_ == $null$)
(ln 12)	assert $assert_9
	goto:
	  if ($r3 != LMain;): Block2
	  if (!($r3 != LMain;)): Block3
Block2:
	goto:
	  Block0
Block3:
(ln 11)	assert ((0 == 0)?false:true)
	goto:
	  Block2

Method <java.lang.Class: boolean desiredAssertionStatus()>($in_0, inHeapCounter)
  Return types: java.lang.Throwable, boolean, int
  Returns: java.lang.Throwable exc, boolean $ret_, int outHeapCounter

Root ->Block0:
(ln 7)	outHeapCounter := inHeapCounter
(ln 7)	exc := $null$
	return

Method <java.lang.Object: void <init>()>($in_0, inHeapCounter)
  Return types: java.lang.Throwable, int
  Returns: java.lang.Throwable exc, int outHeapCounter

Root ->Block0:
(ln 7)	outHeapCounter := inHeapCounter
(ln 7)	exc := $null$
(ln 7)	push_101(java/lang/Object, $in_0, [])
	return


[root] - Hornify  ... 
[root] - Transform Program Methods into Horn Clauses ... 
[root] - Running from entry point: <Main: void main(JayArray_java_lang_String)>
SAFE
```

**Comment by pruemmer** [comment]
I have been trying to hunt this down, but not able to get any further right now. The problem is that the Java expression `UnsatInstOf.class` is translated to a CFG expression (class variable) called `LUnsatInstOf;`, not to `UnsatInstOf`. The strange `L...;` thing already occurs on the Soot level, no idea where it comes from. As a result the class ids don't match up on the Horn level.

**Comment by pruemmer** [comment]
Checked in a workaround for the class name problem.

Now we still have an exception in the ArrayTransformer (this is the problem that occurs in all of the MinePump examples):

```
soottocfg.test.soot_test.SootTranslationTest > test FAILED
    java.lang.NullPointerException
        at soottocfg.soot.transformers.ArrayTransformer.applyTransformation(ArrayTransformer.java:190)
        at soottocfg.soot.SootToCfg.performAbstractionTransformations(SootToCfg.java:307)
        at soottocfg.soot.SootToCfg.run(SootToCfg.java:119)
        at soottocfg.Main.main(Main.java:19)
        at soottocfg.test.soot_test.SootTranslationTest.test(SootTranslationTest.java:38)

```

**Comment by martinschaef** [comment]
lookin
