### ISSUE TITLE
JayHorn crashes when running on itself

### ISSUE THREAD

**Issue by martinschaef** [jayhorn/jayhorn#43]
Exception flies when running:
```
cd jayhorn
gradle jar
cd build
java -jar libs/jayhorn.jar -j classes/main/
```

Stacktrace:
```
Exception in thread "main" java.lang.RuntimeException: couldn't find method <init>([int]) in JayArray_JayArray_int
	at soot.SootClass.getMethod(SootClass.java:509)
	at soottocfg.soot.transformers.ArrayTransformer.applyTransformation(ArrayTransformer.java:225)
	at soottocfg.soot.SootToCfg.performAbstractionTransformations(SootToCfg.java:307)
	at soottocfg.soot.SootToCfg.run(SootToCfg.java:137)
	at jayhorn.Main.safetyAnalysis(Main.java:43)
	at jayhorn.Main.main(Main.java:73)
```

**Comment by martinschaef** [comment]
Narrowed it down:
```java
int[][] foo = new int[1][];
```
crashes ArrayTransformer.java because `int[][] foo` is a multi-array but `new int[1][]` is a `NewArrayExpr` not a `NewMultiArrayExpr` and thus the ArrayTransformer does not find a constructor for the array abstraction class. 
Will fix that in a bit.
