### ISSUE TITLE
JayHorn crashes on trivial program

### ISSUE THREAD

**Issue by pruemmer** [jayhorn/jayhorn#59]
When trying to verify

```
public class Test {
    public int main(String[] args) {
        throw new RuntimeException();
    }
}
```

I get

```
2016-09-14 18:11:37,344 ERROR (main) [root] - java.lang.ArrayIndexOutOfBoundsException: 0
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 0
	at soottocfg.soot.memory_model.PushIdentifierAdder.addToPushesAndPulls(PushIdentifierAdder.java:53)
	at soottocfg.soot.memory_model.PushIdentifierAdder.addIDs(PushIdentifierAdder.java:41)
[...]
```

**Comment by rodykersten** [comment]
At that point, it is assumed that there is 1 entry point to the program. It looks like this somehow passes the earlier check and we end up with a program without entry points in the PushIdentifierAdder.

**Comment by martinschaef** [comment]
I'm adding sth to fail early right now
