### ISSUE TITLE
JayHorn crashes on another trivial program

### ISSUE THREAD

**Issue by pruemmer** [jayhorn/jayhorn#60]
```
public class Test {
    public int x;
    public int main(String[] args) {
        Test a = null;
        a.x = 42;
        return 0;
    }
}
```

gives

```
Exception in thread "main" (<Test: int main(java.lang.String[])>) local type not allowed in final code: null_type local: n0
	at soot.jimple.validation.TypesValidator.validate(TypesValidator.java:44)
	at soot.jimple.JimpleBody.validate(JimpleBody.java:125)
	at soot.jimple.JimpleBody.validate(JimpleBody.java:110)
	at soottocfg.soot.transformers.AssertionReconstruction.reconstructJavaAssertions(AssertionReconstruction.java:283)
```

**Comment by pruemmer** [comment]
It does not make a difference whether "main" is static or not ;-)

**Comment by rodykersten** [comment]
I think this is Soot's way of catching the null dereference. Added a check for that now.
