### ISSUE TITLE
Unequal lengths VerifyException

### ISSUE THREAD

**Issue by rodykersten** [jayhorn/jayhorn#62]
For several of our benchmarks (challenge2onebucket, textcruncher2sort, ImageProcessorMem/simple), I get the following exception:

Unequal lengths: challenge2onebucket/util/HashTable$Entry and [r0_key_4150, r0_value_4161, r0_prev_4172, r0_next_4183, r0_this$0_4194, r0_$dynamicType_6415]
	at com.google.common.base.Verify.verify(Verify.java:123)
	at jayhorn.hornify.encoder.StatementEncoder.pushToClause(StatementEncoder.java:306)
	at jayhorn.hornify.encoder.StatementEncoder.statementToClause(StatementEncoder.java:94)

**Comment by rodykersten** [comment]
Thanks @martinschaef
